# Generated by Django 4.1.7 on 2023-04-11 01:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=255)),
                ('fact_qliq', models.IntegerField()),
                ('fact_qoil', models.IntegerField()),
                ('forecast_qliq', models.IntegerField()),
                ('forecast_qoil', models.IntegerField()),
                ('fact_qliq_2', models.IntegerField()),
                ('fact_qoil_2', models.IntegerField()),
                ('forecast_qliq_2', models.IntegerField()),
                ('forecast_qoil_2', models.IntegerField()),
                ('date', models.DateField(default=datetime.datetime(2022, 6, 1, 0, 0))),
            ],
        ),
    ]
